// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8FhIvErhjnAajVXh36d9a45spCbRavyg',
    appId: '1:750203130851:web:30c1d6a059e9bdb06646d6',
    messagingSenderId: '750203130851',
    projectId: 'plants-green',
    authDomain: 'plants-green.firebaseapp.com',
    databaseURL: 'https://plants-green-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plants-green.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHKjyVXlaKQ7oPTUzuTEtKZ26CFEdHYdc',
    appId: '1:750203130851:android:5ce4e8741d4ee0556646d6',
    messagingSenderId: '750203130851',
    projectId: 'plants-green',
    databaseURL: 'https://plants-green-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plants-green.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQBnuHUFdimbb28WmxITB8HEFML5iSaNA',
    appId: '1:750203130851:ios:26ac5cf9397110826646d6',
    messagingSenderId: '750203130851',
    projectId: 'plants-green',
    databaseURL: 'https://plants-green-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plants-green.appspot.com',
    iosBundleId: 'com.example.plantsGreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQBnuHUFdimbb28WmxITB8HEFML5iSaNA',
    appId: '1:750203130851:ios:26ac5cf9397110826646d6',
    messagingSenderId: '750203130851',
    projectId: 'plants-green',
    databaseURL: 'https://plants-green-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plants-green.appspot.com',
    iosBundleId: 'com.example.plantsGreen',
  );
}
